# Utiliser une image Python officielle
FROM python:3.9-slim

# Installer les dépendances nécessaires
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Copier les fichiers de l'application
COPY . .

# Exposer le port sur lequel Flask fonctionne
EXPOSE 5000

# Démarrer l'application Flask
CMD ["python", "test.py"]

